version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: coffeehybrid-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - coffee-net

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: coffeehybrid-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=${BACKEND_URL}/api
    depends_on:
      - backend
    networks:
      - coffee-net

  bot:
    build:
      context: .
      dockerfile: Bot/Dockerfile
    container_name: coffeehybrid-bot
    restart: always
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - API_BASE_URL=${BACKEND_URL}/api
      - WEBHOOK_URL=${BOT_WEBHOOK_URL}
    depends_on:
      - backend
    networks:
      - coffee-net

networks:
  coffee-net:
    driver: bridge
